format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

# Use the color palette
palette = "dracula"

[directory]
style = "bold green"
format = '[$path]($style)[$read_only]($read_only_style) '

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold green)"

[cmd_duration]
style = "bold yellow"

[git_branch]
style = "bold purple"
format = '\[[$symbol$branch(:$remote_branch)]($style)\]'
symbol=''

[git_commit]
style = "bold cyan"
format = '\[[󰜘$hash]($style)\] '
commit_hash_length = 8
only_detached=false

[git_status]
style = "bold red"

[hostname]
style = "bold purple"

[username]
format = '[$user]($style) on '
style_user = "bold cyan"

# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"